
# set seed ----------------------------------------------------------------


set.seed(24601)


# load packages -----------------------------------------------------------


if (!require(readxl)) {install.packages("readxl")}
if (!require(tidyverse)) {install.packages("tidyverse")}
if (!require(broom)) {install.packages("broom")}
if (!require(coin)) {install.packages("coin")}


# import files ------------------------------------------------------------


butyrate_treatment_interplay_9reps <- read_excel("data/butyrate_treatment_interplay_9reps.xlsx", 
                                                 sheet = "Sheet8")


# rename dataframe --------------------------------------------------------


df_ogint_1 <- butyrate_treatment_interplay_9reps


# check import ------------------------------------------------------------


df_ogint_1


# pivot longer takes col names as a vector to pivot on --------------------


df_ogint_2 <- df_ogint_1 %>% 
        pivot_longer(cols = c('ogint_ctrl_1', 'ogint_ctrl_2', 'ogint_ctrl_3', 'ogint_ctrl_4', 'ogint_ctrl_5', 'ogint_ctrl_6', 'ogint_ctrl_7', 'ogint_ctrl_8', 'ogint_ctrl_9', 'ogint_but_1', 'ogint_but_2', 'ogint_but_3', 'ogint_but_4', 'ogint_but_5', 'ogint_but_6', 'ogint_but_7', 'ogint_but_8', 'ogint_but_9'),
                     names_to = 'sample_name',
                     values_to = 'interplay_score')


# cleaning data and adding treatment conditions ---------------------------


# use str_extract to create sample_name col. 
# regex parses based on underscore - hardcoded to expect int_condition_biorep format
df_ogint_3 <- df_ogint_2 %>% 
        mutate(bio_rep = str_extract(sample_name, "([^_]+)_[^_]+$"))


# use str_extract to create bio_rep col. regex drops based to underscore delim - hardcoded as above
df_ogint_4 <- df_ogint_3 %>% 
        mutate(treatment = str_extract(bio_rep, "^[^_]+"))


df_ogint_5 <- df_ogint_4 %>% 
        select(ptm_combination, bio_rep, treatment, interplay_score, -c(sample_name))

# clean up df_ogint_ for independence tests
df_ogint_6 <- df_ogint_5 %>% 
        select(interplay_score, ptm_combination, treatment)

# drop rows containing K4me3K27un in this data set as err: data are ess constant
df_ogint_7 <- df_ogint_6 %>%
        filter(!grepl('K4me3K27un', ptm_combination))


# KS test for distributions and normality ---------------------------------


df_ogint_8 <- df_ogint_7 %>%
        group_by(ptm_combination, treatment) %>% 
        nest() %>% 
        pivot_wider(names_from = treatment, values_from = data) %>% 
        # depreciated: spread(key = treatment, value = data) %>% 
        mutate(
                ks_test = map2(ctrl, but, ~{ks.test(.x$interplay_score, .y$interplay_score) %>% tidy()}),
                ctrl = map(ctrl, nrow),
                but = map(but, nrow)
        ) %>%
        unnest(cols = c(ctrl, but, ks_test))


# wilcox ranksum test -----------------------------------------------------


df_ogint_9 <- df_ogint_7 %>%
        group_by(ptm_combination, treatment) %>% 
        nest() %>% 
        pivot_wider(names_from = treatment, values_from = data) %>% 
        # depreciated: spread(key = treatment, value = data) %>% 
        mutate(
                wilcox_test = map2(ctrl, but, ~{wilcox.test(.x$interplay_score, .y$interplay_score) %>% tidy()}),
                ctrl = map(ctrl, nrow),
                but = map(but, nrow)
        ) %>% 
        unnest(cols = c(ctrl, but, wilcox_test))


# welch t test ------------------------------------------------------------


df_ogint_10 <- df_ogint_7 %>%
        group_by(ptm_combination, treatment) %>% 
        nest() %>% 
        pivot_wider(names_from = treatment, values_from = data) %>% 
        # depreciated: spread(key = treatment, value = data) %>% 
        mutate(
                t_test = map2(ctrl, but, ~{t.test(.x$interplay_score, .y$interplay_score) %>% tidy()}),
                ctrl = map(ctrl, nrow),
                but = map(but, nrow)
        ) %>% 
        unnest(cols = c(ctrl, but, t_test))


# # No pivot then map permutation test 
# df_ogint_11 <- df_ogint_7 %>%
#         group_by(ptm_combination) %>% 
#         nest() 
# View(df_ogint_11)


# subset dataframes by PTM ------------------------------------------------


df_K4me1K9me1 <- df_ogint_7 %>% filter(grepl('K4me1K9me1', ptm_combination))
df_K4me1K9me2 <- df_ogint_7 %>% filter(grepl('K4me1K9me2', ptm_combination))
df_K4me1K9me3 <- df_ogint_7 %>% filter(grepl('K4me1K9me3', ptm_combination))
df_K4me1K9ac <- df_ogint_7 %>% filter(grepl('K4me1K9ac', ptm_combination))
df_K4me1K9un <- df_ogint_7 %>% filter(grepl('K4me1K9un', ptm_combination))
df_K4me1K14ac <- df_ogint_7 %>% filter(grepl('K4me1K14ac', ptm_combination))
df_K4me1K14un <- df_ogint_7 %>% filter(grepl('K4me1K14un', ptm_combination))
df_K4me1K18ac <- df_ogint_7 %>% filter(grepl('K4me1K18ac', ptm_combination))
df_K4me1K18un <- df_ogint_7 %>% filter(grepl('K4me1K18un', ptm_combination))
df_K4me1K23ac <- df_ogint_7 %>% filter(grepl('K4me1K23ac', ptm_combination))
df_K4me1K23un <- df_ogint_7 %>% filter(grepl('K4me1K23un', ptm_combination))
df_K4me1K27me1 <- df_ogint_7 %>% filter(grepl('K4me1K27me1', ptm_combination))
df_K4me1K27me2 <- df_ogint_7 %>% filter(grepl('K4me1K27me2', ptm_combination))
df_K4me1K27me3 <- df_ogint_7 %>% filter(grepl('K4me1K27me3', ptm_combination))
df_K4me1K27ac <- df_ogint_7 %>% filter(grepl('K4me1K27ac', ptm_combination))
df_K4me1K27un <- df_ogint_7 %>% filter(grepl('K4me1K27un', ptm_combination))
df_K4me1K36me1 <- df_ogint_7 %>% filter(grepl('K4me1K36me1', ptm_combination))
df_K4me1K36me2 <- df_ogint_7 %>% filter(grepl('K4me1K36me2', ptm_combination))
df_K4me1K36me3 <- df_ogint_7 %>% filter(grepl('K4me1K36me3', ptm_combination))
df_K4me1K36un <- df_ogint_7 %>% filter(grepl('K4me1K36un', ptm_combination))
df_K4me2K9me1 <- df_ogint_7 %>% filter(grepl('K4me2K9me1', ptm_combination))
df_K4me2K9me2 <- df_ogint_7 %>% filter(grepl('K4me2K9me2', ptm_combination))
df_K4me2K9me3 <- df_ogint_7 %>% filter(grepl('K4me2K9me3', ptm_combination))
df_K4me2K9ac <- df_ogint_7 %>% filter(grepl('K4me2K9ac', ptm_combination))
df_K4me2K9un <- df_ogint_7 %>% filter(grepl('K4me2K9un', ptm_combination))
df_K4me2K14ac <- df_ogint_7 %>% filter(grepl('K4me2K14ac', ptm_combination))
df_K4me2K14un <- df_ogint_7 %>% filter(grepl('K4me2K14un', ptm_combination))
df_K4me2K18ac <- df_ogint_7 %>% filter(grepl('K4me2K18ac', ptm_combination))
df_K4me2K18un <- df_ogint_7 %>% filter(grepl('K4me2K18un', ptm_combination))
df_K4me2K23ac <- df_ogint_7 %>% filter(grepl('K4me2K23ac', ptm_combination))
df_K4me2K23un <- df_ogint_7 %>% filter(grepl('K4me2K23un', ptm_combination))
df_K4me2K27me1 <- df_ogint_7 %>% filter(grepl('K4me2K27me1', ptm_combination))
df_K4me2K27me2 <- df_ogint_7 %>% filter(grepl('K4me2K27me2', ptm_combination))
df_K4me2K27me3 <- df_ogint_7 %>% filter(grepl('K4me2K27me3', ptm_combination))
df_K4me2K27ac <- df_ogint_7 %>% filter(grepl('K4me2K27ac', ptm_combination))
df_K4me2K27un <- df_ogint_7 %>% filter(grepl('K4me2K27un', ptm_combination))
df_K4me2K36me1 <- df_ogint_7 %>% filter(grepl('K4me2K36me1', ptm_combination))
df_K4me2K36me2 <- df_ogint_7 %>% filter(grepl('K4me2K36me2', ptm_combination))
df_K4me2K36me3 <- df_ogint_7 %>% filter(grepl('K4me2K36me3', ptm_combination))
df_K4me2K36un <- df_ogint_7 %>% filter(grepl('K4me2K36un', ptm_combination))
df_K4me3K9me1 <- df_ogint_7 %>% filter(grepl('K4me3K9me1', ptm_combination))
df_K4me3K9me2 <- df_ogint_7 %>% filter(grepl('K4me3K9me2', ptm_combination))
df_K4me3K9me3 <- df_ogint_7 %>% filter(grepl('K4me3K9me3', ptm_combination))
df_K4me3K9ac <- df_ogint_7 %>% filter(grepl('K4me3K9ac', ptm_combination))
df_K4me3K9un <- df_ogint_7 %>% filter(grepl('K4me3K9un', ptm_combination))
df_K4me3K14ac <- df_ogint_7 %>% filter(grepl('K4me3K14ac', ptm_combination))
df_K4me3K14un <- df_ogint_7 %>% filter(grepl('K4me3K14un', ptm_combination))
df_K4me3K18ac <- df_ogint_7 %>% filter(grepl('K4me3K18ac', ptm_combination))
df_K4me3K18un <- df_ogint_7 %>% filter(grepl('K4me3K18un', ptm_combination))
df_K4me3K23ac <- df_ogint_7 %>% filter(grepl('K4me3K23ac', ptm_combination))
df_K4me3K23un <- df_ogint_7 %>% filter(grepl('K4me3K23un', ptm_combination))
df_K4me3K27me1 <- df_ogint_7 %>% filter(grepl('K4me3K27me1', ptm_combination))
df_K4me3K27me2 <- df_ogint_7 %>% filter(grepl('K4me3K27me2', ptm_combination))
df_K4me3K27me3 <- df_ogint_7 %>% filter(grepl('K4me3K27me3', ptm_combination))
df_K4me3K27ac <- df_ogint_7 %>% filter(grepl('K4me3K27ac', ptm_combination))
df_K4me3K27un <- df_ogint_7 %>% filter(grepl('K4me3K27un', ptm_combination))
df_K4me3K36me1 <- df_ogint_7 %>% filter(grepl('K4me3K36me1', ptm_combination))
df_K4me3K36me2 <- df_ogint_7 %>% filter(grepl('K4me3K36me2', ptm_combination))
df_K4me3K36me3 <- df_ogint_7 %>% filter(grepl('K4me3K36me3', ptm_combination))
df_K4me3K36un <- df_ogint_7 %>% filter(grepl('K4me3K36un', ptm_combination))
df_K4unK9me1 <- df_ogint_7 %>% filter(grepl('K4unK9me1', ptm_combination))
df_K4unK9me2 <- df_ogint_7 %>% filter(grepl('K4unK9me2', ptm_combination))
df_K4unK9me3 <- df_ogint_7 %>% filter(grepl('K4unK9me3', ptm_combination))
df_K4unK9ac <- df_ogint_7 %>% filter(grepl('K4unK9ac', ptm_combination))
df_K4unK9un <- df_ogint_7 %>% filter(grepl('K4unK9un', ptm_combination))
df_K4unK14ac <- df_ogint_7 %>% filter(grepl('K4unK14ac', ptm_combination))
df_K4unK14un <- df_ogint_7 %>% filter(grepl('K4unK14un', ptm_combination))
df_K4unK18ac <- df_ogint_7 %>% filter(grepl('K4unK18ac', ptm_combination))
df_K4unK18un <- df_ogint_7 %>% filter(grepl('K4unK18un', ptm_combination))
df_K4unK23ac <- df_ogint_7 %>% filter(grepl('K4unK23ac', ptm_combination))
df_K4unK23un <- df_ogint_7 %>% filter(grepl('K4unK23un', ptm_combination))
df_K4unK27me1 <- df_ogint_7 %>% filter(grepl('K4unK27me1', ptm_combination))
df_K4unK27me2 <- df_ogint_7 %>% filter(grepl('K4unK27me2', ptm_combination))
df_K4unK27me3 <- df_ogint_7 %>% filter(grepl('K4unK27me3', ptm_combination))
df_K4unK27ac <- df_ogint_7 %>% filter(grepl('K4unK27ac', ptm_combination))
df_K4unK27un <- df_ogint_7 %>% filter(grepl('K4unK27un', ptm_combination))
df_K4unK36me1 <- df_ogint_7 %>% filter(grepl('K4unK36me1', ptm_combination))
df_K4unK36me2 <- df_ogint_7 %>% filter(grepl('K4unK36me2', ptm_combination))
df_K4unK36me3 <- df_ogint_7 %>% filter(grepl('K4unK36me3', ptm_combination))
df_K4unK36un <- df_ogint_7 %>% filter(grepl('K4unK36un', ptm_combination))
df_K9me1K14ac <- df_ogint_7 %>% filter(grepl('K9me1K14ac', ptm_combination))
df_K9me1K14un <- df_ogint_7 %>% filter(grepl('K9me1K14un', ptm_combination))
df_K9me1K18ac <- df_ogint_7 %>% filter(grepl('K9me1K18ac', ptm_combination))
df_K9me1K18un <- df_ogint_7 %>% filter(grepl('K9me1K18un', ptm_combination))
df_K9me1K23ac <- df_ogint_7 %>% filter(grepl('K9me1K23ac', ptm_combination))
df_K9me1K23un <- df_ogint_7 %>% filter(grepl('K9me1K23un', ptm_combination))
df_K9me1K27me1 <- df_ogint_7 %>% filter(grepl('K9me1K27me1', ptm_combination))
df_K9me1K27me2 <- df_ogint_7 %>% filter(grepl('K9me1K27me2', ptm_combination))
df_K9me1K27me3 <- df_ogint_7 %>% filter(grepl('K9me1K27me3', ptm_combination))
df_K9me1K27ac <- df_ogint_7 %>% filter(grepl('K9me1K27ac', ptm_combination))
df_K9me1K27un <- df_ogint_7 %>% filter(grepl('K9me1K27un', ptm_combination))
df_K9me1K36me1 <- df_ogint_7 %>% filter(grepl('K9me1K36me1', ptm_combination))
df_K9me1K36me2 <- df_ogint_7 %>% filter(grepl('K9me1K36me2', ptm_combination))
df_K9me1K36me3 <- df_ogint_7 %>% filter(grepl('K9me1K36me3', ptm_combination))
df_K9me1K36un <- df_ogint_7 %>% filter(grepl('K9me1K36un', ptm_combination))
df_K9me2K14ac <- df_ogint_7 %>% filter(grepl('K9me2K14ac', ptm_combination))
df_K9me2K14un <- df_ogint_7 %>% filter(grepl('K9me2K14un', ptm_combination))
df_K9me2K18ac <- df_ogint_7 %>% filter(grepl('K9me2K18ac', ptm_combination))
df_K9me2K18un <- df_ogint_7 %>% filter(grepl('K9me2K18un', ptm_combination))
df_K9me2K23ac <- df_ogint_7 %>% filter(grepl('K9me2K23ac', ptm_combination))
df_K9me2K23un <- df_ogint_7 %>% filter(grepl('K9me2K23un', ptm_combination))
df_K9me2K27me1 <- df_ogint_7 %>% filter(grepl('K9me2K27me1', ptm_combination))
df_K9me2K27me2 <- df_ogint_7 %>% filter(grepl('K9me2K27me2', ptm_combination))
df_K9me2K27me3 <- df_ogint_7 %>% filter(grepl('K9me2K27me3', ptm_combination))
df_K9me2K27ac <- df_ogint_7 %>% filter(grepl('K9me2K27ac', ptm_combination))
df_K9me2K27un <- df_ogint_7 %>% filter(grepl('K9me2K27un', ptm_combination))
df_K9me2K36me1 <- df_ogint_7 %>% filter(grepl('K9me2K36me1', ptm_combination))
df_K9me2K36me2 <- df_ogint_7 %>% filter(grepl('K9me2K36me2', ptm_combination))
df_K9me2K36me3 <- df_ogint_7 %>% filter(grepl('K9me2K36me3', ptm_combination))
df_K9me2K36un <- df_ogint_7 %>% filter(grepl('K9me2K36un', ptm_combination))
df_K9me3K14ac <- df_ogint_7 %>% filter(grepl('K9me3K14ac', ptm_combination))
df_K9me3K14un <- df_ogint_7 %>% filter(grepl('K9me3K14un', ptm_combination))
df_K9me3K18ac <- df_ogint_7 %>% filter(grepl('K9me3K18ac', ptm_combination))
df_K9me3K18un <- df_ogint_7 %>% filter(grepl('K9me3K18un', ptm_combination))
df_K9me3K23ac <- df_ogint_7 %>% filter(grepl('K9me3K23ac', ptm_combination))
df_K9me3K23un <- df_ogint_7 %>% filter(grepl('K9me3K23un', ptm_combination))
df_K9me3K27me1 <- df_ogint_7 %>% filter(grepl('K9me3K27me1', ptm_combination))
df_K9me3K27me2 <- df_ogint_7 %>% filter(grepl('K9me3K27me2', ptm_combination))
df_K9me3K27me3 <- df_ogint_7 %>% filter(grepl('K9me3K27me3', ptm_combination))
df_K9me3K27ac <- df_ogint_7 %>% filter(grepl('K9me3K27ac', ptm_combination))
df_K9me3K27un <- df_ogint_7 %>% filter(grepl('K9me3K27un', ptm_combination))
df_K9me3K36me1 <- df_ogint_7 %>% filter(grepl('K9me3K36me1', ptm_combination))
df_K9me3K36me2 <- df_ogint_7 %>% filter(grepl('K9me3K36me2', ptm_combination))
df_K9me3K36me3 <- df_ogint_7 %>% filter(grepl('K9me3K36me3', ptm_combination))
df_K9me3K36un <- df_ogint_7 %>% filter(grepl('K9me3K36un', ptm_combination))
df_K9acK14ac <- df_ogint_7 %>% filter(grepl('K9acK14ac', ptm_combination))
df_K9acK14un <- df_ogint_7 %>% filter(grepl('K9acK14un', ptm_combination))
df_K9acK18ac <- df_ogint_7 %>% filter(grepl('K9acK18ac', ptm_combination))
df_K9acK18un <- df_ogint_7 %>% filter(grepl('K9acK18un', ptm_combination))
df_K9acK23ac <- df_ogint_7 %>% filter(grepl('K9acK23ac', ptm_combination))
df_K9acK23un <- df_ogint_7 %>% filter(grepl('K9acK23un', ptm_combination))
df_K9acK27me1 <- df_ogint_7 %>% filter(grepl('K9acK27me1', ptm_combination))
df_K9acK27me2 <- df_ogint_7 %>% filter(grepl('K9acK27me2', ptm_combination))
df_K9acK27me3 <- df_ogint_7 %>% filter(grepl('K9acK27me3', ptm_combination))
df_K9acK27ac <- df_ogint_7 %>% filter(grepl('K9acK27ac', ptm_combination))
df_K9acK27un <- df_ogint_7 %>% filter(grepl('K9acK27un', ptm_combination))
df_K9acK36me1 <- df_ogint_7 %>% filter(grepl('K9acK36me1', ptm_combination))
df_K9acK36me2 <- df_ogint_7 %>% filter(grepl('K9acK36me2', ptm_combination))
df_K9acK36me3 <- df_ogint_7 %>% filter(grepl('K9acK36me3', ptm_combination))
df_K9acK36un <- df_ogint_7 %>% filter(grepl('K9acK36un', ptm_combination))
df_K9unK14ac <- df_ogint_7 %>% filter(grepl('K9unK14ac', ptm_combination))
df_K9unK14un <- df_ogint_7 %>% filter(grepl('K9unK14un', ptm_combination))
df_K9unK18ac <- df_ogint_7 %>% filter(grepl('K9unK18ac', ptm_combination))
df_K9unK18un <- df_ogint_7 %>% filter(grepl('K9unK18un', ptm_combination))
df_K9unK23ac <- df_ogint_7 %>% filter(grepl('K9unK23ac', ptm_combination))
df_K9unK23un <- df_ogint_7 %>% filter(grepl('K9unK23un', ptm_combination))
df_K9unK27me1 <- df_ogint_7 %>% filter(grepl('K9unK27me1', ptm_combination))
df_K9unK27me2 <- df_ogint_7 %>% filter(grepl('K9unK27me2', ptm_combination))
df_K9unK27me3 <- df_ogint_7 %>% filter(grepl('K9unK27me3', ptm_combination))
df_K9unK27ac <- df_ogint_7 %>% filter(grepl('K9unK27ac', ptm_combination))
df_K9unK27un <- df_ogint_7 %>% filter(grepl('K9unK27un', ptm_combination))
df_K9unK36me1 <- df_ogint_7 %>% filter(grepl('K9unK36me1', ptm_combination))
df_K9unK36me2 <- df_ogint_7 %>% filter(grepl('K9unK36me2', ptm_combination))
df_K9unK36me3 <- df_ogint_7 %>% filter(grepl('K9unK36me3', ptm_combination))
df_K9unK36un <- df_ogint_7 %>% filter(grepl('K9unK36un', ptm_combination))
df_K14acK18ac <- df_ogint_7 %>% filter(grepl('K14acK18ac', ptm_combination))
df_K14acK18un <- df_ogint_7 %>% filter(grepl('K14acK18un', ptm_combination))
df_K14acK23ac <- df_ogint_7 %>% filter(grepl('K14acK23ac', ptm_combination))
df_K14acK23un <- df_ogint_7 %>% filter(grepl('K14acK23un', ptm_combination))
df_K14acK27me1 <- df_ogint_7 %>% filter(grepl('K14acK27me1', ptm_combination))
df_K14acK27me2 <- df_ogint_7 %>% filter(grepl('K14acK27me2', ptm_combination))
df_K14acK27me3 <- df_ogint_7 %>% filter(grepl('K14acK27me3', ptm_combination))
df_K14acK27ac <- df_ogint_7 %>% filter(grepl('K14acK27ac', ptm_combination))
df_K14acK27un <- df_ogint_7 %>% filter(grepl('K14acK27un', ptm_combination))
df_K14acK36me1 <- df_ogint_7 %>% filter(grepl('K14acK36me1', ptm_combination))
df_K14acK36me2 <- df_ogint_7 %>% filter(grepl('K14acK36me2', ptm_combination))
df_K14acK36me3 <- df_ogint_7 %>% filter(grepl('K14acK36me3', ptm_combination))
df_K14acK36un <- df_ogint_7 %>% filter(grepl('K14acK36un', ptm_combination))
df_K14unK18ac <- df_ogint_7 %>% filter(grepl('K14unK18ac', ptm_combination))
df_K14unK18un <- df_ogint_7 %>% filter(grepl('K14unK18un', ptm_combination))
df_K14unK23ac <- df_ogint_7 %>% filter(grepl('K14unK23ac', ptm_combination))
df_K14unK23un <- df_ogint_7 %>% filter(grepl('K14unK23un', ptm_combination))
df_K14unK27me1 <- df_ogint_7 %>% filter(grepl('K14unK27me1', ptm_combination))
df_K14unK27me2 <- df_ogint_7 %>% filter(grepl('K14unK27me2', ptm_combination))
df_K14unK27me3 <- df_ogint_7 %>% filter(grepl('K14unK27me3', ptm_combination))
df_K14unK27ac <- df_ogint_7 %>% filter(grepl('K14unK27ac', ptm_combination))
df_K14unK27un <- df_ogint_7 %>% filter(grepl('K14unK27un', ptm_combination))
df_K14unK36me1 <- df_ogint_7 %>% filter(grepl('K14unK36me1', ptm_combination))
df_K14unK36me2 <- df_ogint_7 %>% filter(grepl('K14unK36me2', ptm_combination))
df_K14unK36me3 <- df_ogint_7 %>% filter(grepl('K14unK36me3', ptm_combination))
df_K14unK36un <- df_ogint_7 %>% filter(grepl('K14unK36un', ptm_combination))
df_K18acK23ac <- df_ogint_7 %>% filter(grepl('K18acK23ac', ptm_combination))
df_K18acK23un <- df_ogint_7 %>% filter(grepl('K18acK23un', ptm_combination))
df_K18acK27me1 <- df_ogint_7 %>% filter(grepl('K18acK27me1', ptm_combination))
df_K18acK27me2 <- df_ogint_7 %>% filter(grepl('K18acK27me2', ptm_combination))
df_K18acK27me3 <- df_ogint_7 %>% filter(grepl('K18acK27me3', ptm_combination))
df_K18acK27ac <- df_ogint_7 %>% filter(grepl('K18acK27ac', ptm_combination))
df_K18acK27un <- df_ogint_7 %>% filter(grepl('K18acK27un', ptm_combination))
df_K18acK36me1 <- df_ogint_7 %>% filter(grepl('K18acK36me1', ptm_combination))
df_K18acK36me2 <- df_ogint_7 %>% filter(grepl('K18acK36me2', ptm_combination))
df_K18acK36me3 <- df_ogint_7 %>% filter(grepl('K18acK36me3', ptm_combination))
df_K18acK36un <- df_ogint_7 %>% filter(grepl('K18acK36un', ptm_combination))
df_K18unK23ac <- df_ogint_7 %>% filter(grepl('K18unK23ac', ptm_combination))
df_K18unK23un <- df_ogint_7 %>% filter(grepl('K18unK23un', ptm_combination))
df_K18unK27me1 <- df_ogint_7 %>% filter(grepl('K18unK27me1', ptm_combination))
df_K18unK27me2 <- df_ogint_7 %>% filter(grepl('K18unK27me2', ptm_combination))
df_K18unK27me3 <- df_ogint_7 %>% filter(grepl('K18unK27me3', ptm_combination))
df_K18unK27ac <- df_ogint_7 %>% filter(grepl('K18unK27ac', ptm_combination))
df_K18unK27un <- df_ogint_7 %>% filter(grepl('K18unK27un', ptm_combination))
df_K18unK36me1 <- df_ogint_7 %>% filter(grepl('K18unK36me1', ptm_combination))
df_K18unK36me2 <- df_ogint_7 %>% filter(grepl('K18unK36me2', ptm_combination))
df_K18unK36me3 <- df_ogint_7 %>% filter(grepl('K18unK36me3', ptm_combination))
df_K18unK36un <- df_ogint_7 %>% filter(grepl('K18unK36un', ptm_combination))
df_K23acK27me1 <- df_ogint_7 %>% filter(grepl('K23acK27me1', ptm_combination))
df_K23acK27me2 <- df_ogint_7 %>% filter(grepl('K23acK27me2', ptm_combination))
df_K23acK27me3 <- df_ogint_7 %>% filter(grepl('K23acK27me3', ptm_combination))
df_K23acK27ac <- df_ogint_7 %>% filter(grepl('K23acK27ac', ptm_combination))
df_K23acK27un <- df_ogint_7 %>% filter(grepl('K23acK27un', ptm_combination))
df_K23acK36me1 <- df_ogint_7 %>% filter(grepl('K23acK36me1', ptm_combination))
df_K23acK36me2 <- df_ogint_7 %>% filter(grepl('K23acK36me2', ptm_combination))
df_K23acK36me3 <- df_ogint_7 %>% filter(grepl('K23acK36me3', ptm_combination))
df_K23acK36un <- df_ogint_7 %>% filter(grepl('K23acK36un', ptm_combination))
df_K23unK27me1 <- df_ogint_7 %>% filter(grepl('K23unK27me1', ptm_combination))
df_K23unK27me2 <- df_ogint_7 %>% filter(grepl('K23unK27me2', ptm_combination))
df_K23unK27me3 <- df_ogint_7 %>% filter(grepl('K23unK27me3', ptm_combination))
df_K23unK27ac <- df_ogint_7 %>% filter(grepl('K23unK27ac', ptm_combination))
df_K23unK27un <- df_ogint_7 %>% filter(grepl('K23unK27un', ptm_combination))
df_K23unK36me1 <- df_ogint_7 %>% filter(grepl('K23unK36me1', ptm_combination))
df_K23unK36me2 <- df_ogint_7 %>% filter(grepl('K23unK36me2', ptm_combination))
df_K23unK36me3 <- df_ogint_7 %>% filter(grepl('K23unK36me3', ptm_combination))
df_K23unK36un <- df_ogint_7 %>% filter(grepl('K23unK36un', ptm_combination))
df_K27me1K36me1 <- df_ogint_7 %>% filter(grepl('K27me1K36me1', ptm_combination))
df_K27me1K36me2 <- df_ogint_7 %>% filter(grepl('K27me1K36me2', ptm_combination))
df_K27me1K36me3 <- df_ogint_7 %>% filter(grepl('K27me1K36me3', ptm_combination))
df_K27me1K36un <- df_ogint_7 %>% filter(grepl('K27me1K36un', ptm_combination))
df_K27me2K36me1 <- df_ogint_7 %>% filter(grepl('K27me2K36me1', ptm_combination))
df_K27me2K36me2 <- df_ogint_7 %>% filter(grepl('K27me2K36me2', ptm_combination))
df_K27me2K36me3 <- df_ogint_7 %>% filter(grepl('K27me2K36me3', ptm_combination))
df_K27me2K36un <- df_ogint_7 %>% filter(grepl('K27me2K36un', ptm_combination))
df_K27me3K36me1 <- df_ogint_7 %>% filter(grepl('K27me3K36me1', ptm_combination))
df_K27me3K36me2 <- df_ogint_7 %>% filter(grepl('K27me3K36me2', ptm_combination))
df_K27me3K36me3 <- df_ogint_7 %>% filter(grepl('K27me3K36me3', ptm_combination))
df_K27me3K36un <- df_ogint_7 %>% filter(grepl('K27me3K36un', ptm_combination))
df_K27acK36me1 <- df_ogint_7 %>% filter(grepl('K27acK36me1', ptm_combination))
df_K27acK36me2 <- df_ogint_7 %>% filter(grepl('K27acK36me2', ptm_combination))
df_K27acK36me3 <- df_ogint_7 %>% filter(grepl('K27acK36me3', ptm_combination))
df_K27acK36un <- df_ogint_7 %>% filter(grepl('K27acK36un', ptm_combination))
df_K27unK36me1 <- df_ogint_7 %>% filter(grepl('K27unK36me1', ptm_combination))
df_K27unK36me2 <- df_ogint_7 %>% filter(grepl('K27unK36me2', ptm_combination))
df_K27unK36me3 <- df_ogint_7 %>% filter(grepl('K27unK36me3', ptm_combination))
df_K27unK36un <- df_ogint_7 %>% filter(grepl('K27unK36un', ptm_combination))


# permutation test on filtered data ---------------------------------------


independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K9me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K9me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K9me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K9ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K9un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me1K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K9me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K9me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K9me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K9ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K9un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me2K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K9me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K9me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K9me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K9ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K9un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4me3K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK9me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK9me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK9me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK9ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK9un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K4unK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me1K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me2K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9me3K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9acK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK14ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK14un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K9unK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14acK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK18ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK18un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K14unK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18acK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK23ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK23un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K18unK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23acK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK27me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK27me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK27me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK27ac, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK27un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K23unK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me1K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me1K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me1K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me1K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me2K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me2K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me2K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me2K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me3K36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me3K36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me3K36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27me3K36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27acK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27acK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27acK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27acK36un, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27unK36me1, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27unK36me2, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27unK36me3, distribution = approximate(1000000))
independence_test(interplay_score ~ as.factor(treatment), data = df_K27unK36un, distribution = approximate(1000000))
